version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "mysql_db"
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysqldata/MySql:/var/lib/mysql